# --- General ---
set -g mouse on
set -g default-terminal "tmux-256color"
set -sg escape-time 0

# --- Window ---
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1

# --- Keybindings ---
bind-key S set-window-option synchronize-panes
