# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""  # using starship instead
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Load modules
DOTFILES_ZSH="$(dirname "$(readlink -f ~/.zshrc)")"
source "$DOTFILES_ZSH/env.zsh"
source "$DOTFILES_ZSH/aliases.zsh"
source "$DOTFILES_ZSH/tools.zsh"
